### ISSUE TITLE
Add redirects from rust-lang-nursery.github.io

### ISSUE THREAD

**Issue by wesleyjellis** [rustwasm/book#1]
I had bookmarked https://rust-lang-nursery.github.io/rust-wasm/game-of-life/introduction.html to check out later, but was surprised today to find that the link was dead. It would be nice to leave some kind of redirect in place to the new home of the rust wasm book (which is https://rustwasm.github.io/book/game-of-life/introduction.html for those that are too lazy to go find it)

(also woo first issue!)

**Comment by fitzgen** [comment]
We have a redirect for the rust-lang-nursery.github.io/rust-wasm/index.html in place. I'd be super happy to merge a PR that copied that into every relevant `path/to/file.html` in https://github.com/rust-lang-nursery/rust-wasm/

**Comment by fitzgen** [comment]
I don't think it is worth doing this anymore.
