### ISSUE TITLE
Should 'wasm-pack init' be change to 'wasm-pack build'

### ISSUE THREAD

**Issue by davidMcneil** [rustwasm/book#102]
**Where in the docs did you come across this?**
The end of the "Hello World!" chapter. Where it says "Anytime you make changes and want them reflected on http://localhost:8080/, just re-run the wasm-pack init command within the wasm-game-of-life directory."

**Describe what about it does not make sense**
I believe it should 'wasm-pack build' instead of  'wasm-pack init'.

**Why does it not make sense?**
 'wasm-pack init' is deprecated.

**How could we improve it?**
Change it to  'wasm-pack build'

**Comment by jjpe** [comment]
Just saw this myself, an easily clickable link is [here](https://rustwasm.github.io/book/game-of-life/hello-world.html#serving-locally).
