### ISSUE TITLE
Question: separate or combined Issues/PRs for multiple docs suggestions

### ISSUE THREAD

**Issue by 0xazure** [rustwasm/book#115]
I just discovered the Rust WASM book today, and I'm really excited to start playing around with Rust in the browser.

As I've been reading through the book I've come across a few places where I think the docs could be improved, and related to #28 I wanted to find out if there is any preference for creating a separate Issue and/or PR for each (possibly unrelated) suggestion, or if each suggestion should have its own Issue and/or PR.

Thanks!

**Comment by fitzgen** [comment]
Separate issues are helpful because we can close issue X when we fix it, even if there are still open questions around issue Y, and so the fix for Y isn't ready to land yet, and that doesn't stop us from making progress on issue X.

Excited to get your feedback!

**Comment by 0xazure** [comment]
@fitzgen Thanks so much for the quick reply!

I figured separate PRs would be preferred, but I wanted to ask just to make sure and to save me having to split or merge PRs at a later date.

Really looking forward to digging into the book, and I should have some feedback this week once I polish it up a bit.
