### ISSUE TITLE
wasm-pack tutorial out of date #174

### ISSUE THREAD

**Issue by jrichocean** [rustwasm/book#14]
[Link to old issue](https://github.com/rustwasm/team/issues/174)

Issue Opened by @mgattozzi 

This was brought up in the example repo and the code has been updated there but we need to also update the code in the tutorial here.

[mgattozzi/wasm-add#1 (comment)](https://github.com/mgattozzi/wasm-add/issues/1#issuecomment-388124867)

@adityac8 said they would do this and update the book here.

**Comment by fitzgen** [comment]
The wasm-pack tutorial moved into the wasm-pack repo, please refile this issue there if it is still relevant.
