### ISSUE TITLE
The step-by-step tutorial doesn't work

### ISSUE THREAD

**Issue by Aloso** [rustwasm/book#144]
I tried it several times. I made sure that I executed the commands in the correct directories. Still, the tutorial https://rustwasm.github.io/book/ doesn't work: When I open the website, the alert says `Hello, hello-wasm-pack!` instead of `Hello, wasm-game-of-life!`

The greet function in `/src/lib.rs` looks like this:

```rust
#[wasm_bindgen]
pub fn greet() {
    alert("Hello, wasm-game-of-life!");
}
```

When I modify the function and execute `wasm-pack build` again, it does not have any effect. It looks like a different function is used.

According to npm, the directories are linked as following:

    ~/Develop/wasm-game-of-life/www/node_modules/wasm-game-of-life
       ->  ~/.npm/lib/node_modules/wasm-game-of-life  ->  ~/Develop/wasm-game-of-life/pkg

I looked into several wasm files in these folders. It looks like the `hello_wasm_pack_bg.wasm` file in the node module `hello-wasm-pack` is used, instead of the one generated by `wasm-pack`.

Did I do something wrong, or is my node installation misconfigured, or is the tutorial no longer valid?

**Additional context**
- Manjaro linux
- node v11.6.0
- wasm-pack 0.5.1
- rustc 1.31.0 (abe02cefd 2018-12-04), stable toolchain

**Comment by Aloso** [comment]
@fitzgen  The file says

```javascript
import * as wasm from "hello-wasm-pack";

wasm.greet();
```

I guess that explains why it doesn't work. I'm no expert for NPM though.

**Comment by fitzgen** [comment]
I think you skipped this step:

https://rustwasm.github.io/book/game-of-life/hello-world.html#using-our-local-wasm-game-of-life-package-in-www

> Finally, modify wasm-game-of-life/www/index.js to import wasm-game-of-life instead of the hello-wasm-pack package:

**Comment by Aloso** [comment]
Nope! I did execute `npm link` in the `wasm-game-of-life/pkg` directory.

**Comment by Aloso** [comment]
@fitzgen This is the whole procedure:

1. `npm install npm@latest -g`

1. `cargo generate --git https://github.com/rustwasm/wasm-pack-template`
    - Enter project name

1. In `<project-name>`:
    - `wasm-pack build`
    - `npm init wasm-app www`

1. In `<project-name>/www`:
    - `npm install`

1. In `<project-name>/pkg`:
    - `npm link`

1. In `<project-name>/www`:
    - `npm link <project-name>`

1. In `<project-name>/www/index.js`:
    - Change first line to `import * as wasm from "hello-wasm-pack";`

I believe most of this could be automated.

**Comment by sj4nes** [comment]
Step 3b fails for me silently and does not create the `www` directory.  I'm filling in the defaults when prompted and typing 'yes' to accept--which turns out to be a symptom of the issue. My stumble was an older version of npm was hiding in the path-- when the command is successful you will see something like:

```
$ npm init wasm-app www
npx: installed 1 in 1.662s
🦀 Rust + 🕸 Wasm = ❤
```
You are not prompted for any parameters in this case.

(Writing this in case anyone else is going.. "huh?" why didn't it work?)
