### ISSUE TITLE
Update wasm-pack tutorial paths #154

### ISSUE THREAD

**Issue by jrichocean** [rustwasm/book#15]
[Link to old issue](https://github.com/rustwasm/team/issues/154)

This issue was opened by @mgattozzi 

We're just waiting for a 0.2 release of wasm-pack right now for this issue. In [https://github.com/rust-lang-nursery/rust-wasm/pull/151](https://github.com/rust-lang-nursery/rust-wasm/pull/151) we changed a path reference from `./node_modules/@MYSCOPE/wasm-add/wasm_add.js` to `@MYSCOPE/wasm-add/wasm_add.js`. As was noted in [#151](https://github.com/rustwasm/team/pull/151) after [ashleygwilliams/wasm-pack#94](https://github.com/ashleygwilliams/wasm-pack/issues/94) is closed we can shorten this further to @MYSCOPE/wasm-add which is more idiomatic for JS.

Mentoring instructions:

1. In `src/wasm-pack/run-the-code.md` change the import statement of index.js to the above statement.
2. Test that the changes work as part of the tutorial with the new syntax

**Comment by fitzgen** [comment]
The wasm-pack tutorial moved into the wasm-pack repo, please refile this issue there if it is still relevant.
