### ISSUE TITLE
Section numbers are off

### ISSUE THREAD

**Issue by jrvidal** [rustwasm/book#158]
1->2->3->5->7 :thinking: 

I compiled locally with `mdbook` 0.2.3 and it fixed it, but I imagine that somebody with access will have to deploy manually?

![Screenshot at 2019-03-14 20:38:59](https://user-images.githubusercontent.com/1636604/54386513-6205d200-4699-11e9-81bd-d5457b53cbd0.png)

**Comment by alexcrichton** [comment]
Thanks for the report! It's actually fixed in this repository but forgot to fix it in a different repository!
