### ISSUE TITLE
Add a wasm-bindgen hello world to the book #127

### ISSUE THREAD

**Issue by jrichocean** [rustwasm/book#16]
[Link to old issue](https://github.com/rustwasm/team/issues/127)

Issue was opened by @johnthagen 

I found Alex's blog post on wasm-bindgen to be extremely enlightening: [https://hacks.mozilla.org/2018/04/javascript-to-rust-and-back-again-a-wasm-bindgen-tale/](https://hacks.mozilla.org/2018/04/javascript-to-rust-and-back-again-a-wasm-bindgen-tale/)

Could something along these lines be brought into the book, perhaps even in hello world style? It seems like the next step after learning how to expose C ABI functions like those in the current hello world example.

If this was brought into the book, it could be maintained as the ecosystem evolves.

The stuff he describes in his blog seems simpler than jumping straight to Conway's Game of Life.

**Comment by fitzgen** [comment]
The game of life tutorial contains a hello world using wasm-bindgen within it. I think we can consider this done.
