### ISSUE TITLE
Link to "host bindings proposal" is broken.

### ISSUE THREAD

**Issue by cldershem** [rustwasm/book#162]
**Describe the bug**
The link in the [Implementing Life](https://rustwasm.github.io/docs/book/game-of-life/implementing.html#interfacing-rust-and-javascript) section of the book to ["host bindings proposal"](https://rustwasm.github.io/docs/book/game-of-life/implementing.html) is broken.

**To Reproduce**
1. Go to [the book](https://rustwasm.github.io/docs/book/game-of-life/implementing.html#interfacing-rust-and-javascript)
2. Click on  '"host bindings" proposal'
3. See error

**Expected behavior**
It is unclear what page is expected to load, possibly this [explainer](https://github.com/WebAssembly/webidl-bindings/blob/master/proposals/webidl-bindings/Explainer.md).

**Screenshots**
n/a

**Additional context**
It appears that "host bindings" has been renamed and that there have been some significant changes since the book was last updated. See [issue #21](https://github.com/WebAssembly/webidl-bindings/pull/21) for more context.

**Comment by alexcrichton** [comment]
Thanks! I've [updated the link](https://github.com/rustwasm/book/commit/3a9c4aeb707345c9781790301842e59fe1400b1d) and it should propagate to the website in a few minutes.
