### ISSUE TITLE
silly fetchPackageMetaData error for wasm-game-of-life@file: ../pkg Could not install from " ../pkg" as it does not contain a package.json file

### ISSUE THREAD

**Issue by magj2006** [rustwasm/book#191]
I followed the steps of book, but got this error when I run command 'npm install' in www.  and I checked there is a package.json in pkg directory.

<img width="972" alt="屏幕快照 2019-10-04 下午1 38 21" src="https://user-images.githubusercontent.com/8394789/66193842-db542900-e6ac-11e9-8363-462bbfe8e091.png">

**Comment by magj2006** [comment]
it‘ OK now.

**Comment by Dygear** [comment]
Ok. What did you do? How did you fix this?

**Comment by Dygear** [comment]
Also, these issues might be linked. https://github.com/rustwasm/wasm-pack/issues/913

If the above fails, the `package.json` is never created in the `pkg` directory.

**Comment by magj2006** [comment]
> Ok. What did you do? How did you fix this?

@Dygear Sorry, see it today.  It have been long time, so I forgot it.

**Comment by lisiur** [comment]
I also encountered the same problem, the reason is that there is an extra space in front of `../pkg`.
change `file: ../pkg` to `file:../pkg`
