### ISSUE TITLE
Created a wasm-rust programming environment docker. May make running the initial tutorials way easier for some

### ISSUE THREAD

**Issue by btassone** [rustwasm/book#197]
Wasn't sure where else to message the maintainers of this project about this.

Spent some time the past day or so creating a basic programming environment container for wasm + rust.

[Check it out here](https://hub.docker.com/r/btassone/wasm-rust)

Just make a docker-compose.yml file like in the readme and follow the few instructions. Should have anyone struggling to set anything up running in < 5 minutes.

I hope posting this here isn't a problem, just figured it might help out some people.

**Comment by elazar** [comment]
I've created a [slightly more minimal Docker image](https://gist.github.com/elazar/08323ee3659beba267acae6305c8e840) for use with the rustwasm book.

It's based on [Alpine](https://www.alpinelinux.org) and uses the [setup used for the Game of Life example](https://rustwasm.github.io/docs/book/game-of-life/setup.html).
