### ISSUE TITLE
Split Book into Four Sections #85

### ISSUE THREAD

**Issue by jrichocean** [rustwasm/book#20]
[link to old issue](https://github.com/rustwasm/team/issues/85)

Issue opened by @mgattozzi 

Today in the WG meeting we discussed who wasm and this book is for and we struck upon three groups:

1. Those who want to use wasm in a JS library
2. Those who want to use Rust only for a web app via wasm
3. Those who want to use wasm as a cross platform binary and not just the web

Each group has different restrictions and wants. For instance those who would want to run a wasm executable file on a computer could care less about how to do JS interop. Those wishing to interact with JS would want to know however.

This creates a bit of a conflict when developing the documentation. They'll have to skip sections they might not want to read. Even worse if this is their first introduction to wasm and what they want to use it for they will likely be left confused.

This leads us to the current goal: splitting up the book. It'll be four sections:

1. Things that span all three groups, such as setting up the tool chain, what wasm is etc.
2. Library for JS - Tools, tutorials, information etc. specific to this domain
3. Pure Rust Web App - Tools, tutorials, information etc. specific to this domain
4. Universal Binary - Tools, tutorials, information etc. specific to this domain

 for this include:

- [ ]  Restructure the book to have the 4 top level sections and an introduction explaining that
- [ ]  Breaking out what's currently there into the four sections
- [ ]  Provide some external resources for those sections not currently expanded much

**Comment by mgattozzi** [comment]
As we've kind of refocused what we want to do in the book for the 2018 edition I'm closing this in favor of #44
