### ISSUE TITLE
Downplay cost of calling between JS <--> wasm

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/book#29]
In https://rustwasm.github.io/book/game-of-life/implementing.html#interfacing-rust-and-javascript we describe calling between wasm and JS as something that is potentially expensive and that one should try and minimize. My understanding is that this may be unnecessary now, and that all engines have low-overhead paths for these calls.

@bnjbvr, maybe you can say a little more about this and confirm/deny it? Do you have any suggested edits to point (3) in the section linked above? Thanks!

**Comment by bnjbvr** [comment]
It's an old caveat that doesn't quite apply today, at least in Chrome and Firefox. I haven't tested recently in Edge nor Safari. For instance on Firefox, recent work has made most calls from JS to wasm as well as the other direction fast enough in most cases (from [Firefox 60](https://bugzilla.mozilla.org/show_bug.cgi?id=1319203)). While there's still room for relative improvement ([monomorphic optimizations](https://bugzilla.mozilla.org/show_bug.cgi?id=1437065), cross-world inlining which is harder to accomplish), we're in a better place and I don't think we should recommend to limit those calls anymore. If there's a case where the calls are very slow, it is likely to be a bug.

**Comment by mgattozzi** [comment]
Mentoring Instructions:

1) Identify every place mentioning JS <-> wasm calls
2) Remove them
3) Smooth out wording in surrounding areas so that the flow of the article doesn't feel off.

Point 3 is likely the hardest part and the easiest way to do so is to reread the article after 2 is completed and smoothing over any part that feels off

**Comment by alfiedotwtf** [comment]
As mentioned in the pull comments, 3) didn't seem like a problem if the offending paragraphs were removed. Also, couldn't find anymore mentions that seemed related.

**Comment by mgattozzi** [comment]
Perfect thanks @alfiedotwtf! I think we can consider this closed and if there's anything unclear we can open up separate issues.

**Comment by fitzgen** [comment]
Thanks for enlightening us @bnjbvr :)
