### ISSUE TITLE
Write a CONTRIBUTING.md

### ISSUE THREAD

**Issue by mgattozzi** [rustwasm/book#3]
We need to write up how people can contribute. Also need to update the corresponding goals doc on rustwasm/team

**Comment by sendilkumarn** [comment]
Also can we make sure that the projects in the org should all have something similar?

**Comment by mgattozzi** [comment]
If they don't already they'll need to! However, that's outside the scope of this repo so I'm going to cc/ @rustwasm/core on this so that can be coordinated elsewhere

**Comment by fitzgen** [comment]
Would love to see every project have `CONTRIBUTING.md`! Just need people to do the work :)

**Comment by mgattozzi** [comment]
Closed in #30
