### ISSUE TITLE
wasm_game_of_life_bg is unexplained

### ISSUE THREAD

**Issue by alfiedotwtf** [rustwasm/book#38]
Reading the docs, there's the following code to add when trying out the examples:

    import { memory } from "./wasm_game_of_life_bg";

Yet, nowhere does it explain what memory() does or where wasm_game_of_life_bg came from?

**Comment by fitzgen** [comment]
`memory` is the wasm instance's linear memory, and `wasm_game_of_life_bg` is the "raw" wasm module without the generated JS bindings.

Would you be interested in sending a PR to clarify this?

**Comment by alfiedotwtf** [comment]
Sure!

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rustwasm/book/pull/42
