### ISSUE TITLE
Setup exercise has confusing hint

### ISSUE THREAD

**Issue by tlively** [rustwasm/book#39]
**Where in the docs did you come across this?**

The second exercise at https://rustwasm.github.io/book/game-of-life/setup.html#exercises suggests introducing an error (passing one argument to a Rust function expecting two) and looking at the developer tools to see the results.

**Describe what about it does not make sense**

The hint to look at the developer tools makes me think I should see an error in the console, but I see... nothing!

**Why does it not make sense?**

The wording of the exercise sets me up to believe that it will demonstrate some sort of error reporting, but the result is the opposite of that.

**How could we improve it?**

Explicitly state the expected results, so I can't be surprised by what I find.

P.S. Was there supposed to be an error message? I'm paranoid that I screwed something up and did not get the expected results. The book doesn't tell me!

**Comment by fitzgen** [comment]
There was supposed to be an error message in the console... I'm actually not sure if there ever was and if this is a regression or not.

I'm getting an empty string for the new parameter now though.
