### ISSUE TITLE
plan of translate chinese 🇨🇳

### ISSUE THREAD

**Issue by chinanf-boy** [rustwasm/book#41]
## Add `h2|h*` to source `readme.md`

```
## Translations

- [![china](https://raw.githubusercontent.com/gosquared/flags/master/flags/flags/shiny/24/China.png) **中文/Chinese**](https://github.com/chinanf-boy/rustwasm-book)

```

---

## Translations

- [![china](https://raw.githubusercontent.com/gosquared/flags/master/flags/flags/shiny/24/China.png) **中文/Chinese**](https://github.com/chinanf-boy/rustwasm-book)

## I can finish tomorrow 😊

**Comment by mgattozzi** [comment]
This would be great to add, thank you! :D

**Comment by chinanf-boy** [comment]
I finish 😊

**Comment by mgattozzi** [comment]
@chinanf-boy I have had a very busy month. Is this available anywhere?

**Comment by chinanf-boy** [comment]
I see, I will check it later

**Comment by chinanf-boy** [comment]
Seem like the folder of `wasm-pack` was got , 

I can update the md file, but my MAC computer has been repaired. It will take the whole week, so the Chinese content on my website http://llever.com/rustwasm-book/ will be updated next month.
