### ISSUE TITLE
How do you fire the fps timer?

### ISSUE THREAD

**Issue by alfiedotwtf** [rustwasm/book#43]
In "8.1.6. Time Profiling", there is an `fps` timer created. But as my Javascript is lacking, I'm not able to follow along with the current documentation on where to add the code to trigger the render().

**Comment by fitzgen** [comment]
One would add a call to `fps.render()` within the `renderLoop` function:

> For example, we can create a simple FPS counter **that we update on each iteration of our renderLoop**:

Happy to receive another PR that makes this more clear!

**Comment by mgattozzi** [comment]
Easy issue while I'm gone for IRR @sarahmeyer and @nanoplink
