### ISSUE TITLE
Publishing section of Game of Life Tutorial

### ISSUE THREAD

**Issue by mgattozzi** [rustwasm/book#45]
We will actually want to write this one out instead of leaving it as `Coming Soon`. This is a tracking issue for it until that changes.

There's some discussion of how we want to do this in #16 and might still need more discussion

**Comment by mgattozzi** [comment]
@sarahmeyer and @nanoplink this might be a good one to do if you feel like directly interacting and sussing out questions with the team in #16 and then actually implementing it :D

**Comment by mgattozzi** [comment]
@fitzgen Do we want this to be in conjunction with #26

**Comment by fitzgen** [comment]
Did this as part of #78
