### ISSUE TITLE
Dependencies not up to date

### ISSUE THREAD

**Issue by zixuanzh** [rustwasm/book#51]
**Where in the docs did you come across this?**
I am new to Rust and I am coding along tutorial on Game of Life. 
**Describe what about it does not make sense**
Cargo.lock is not up to date as dependencies have bumped up their versions.
**Why does it not make sense?**
Rust fails to compile
**How could we improve it?**
update proc-macro2 to latest v0.4.9 `cargo update -p proc-macro2`
update wasm-bindgen to latest v0.2.13 `cargo update -p wasm-bindgen`

**Comment by fitzgen** [comment]
Fixed in https://github.com/rustwasm/wasm_game_of_life/pull/24 -- thanks for filing an issue!
