### ISSUE TITLE
dead link in time-profiling.html

### ISSUE THREAD

**Issue by sigmaSd** [rustwasm/book#57]
https://rustwasm.github.io/book/game-of-life/time-profiling.html#developer-tools-profilers
Under **Developer Tools Profilers** , the link `build with debug symbols` is wrong (gives 404 error) .
I tried fixing it but I got so many different results, for example it actually works with mdbook serve .
However if I build with mdbook build then visit the page manually, it doesn't work but in this case its fixed by appending `..` to the link path.

**Comment by mgattozzi** [comment]
Ah so looking at this the link is going to:

`https://rustwasm.github.io/game-of-life/debugging.html#building-with-debug-symbols`

But it should be:

`https://rustwasm.github.io/book/game-of-life/debugging.html#building-with-debug-symbols`

It's missing the `/book/` part of the link. Want an easy PR to fix it? :)

**Comment by sigmaSd** [comment]
Not sure if I'm over-complicating things, but the problem is _I can't test my changes ,_ with github preview all links are dead even screenshots links , locally with mdbook serve it works out of the box but with mdbook build all links are dead (even screenshots) .
However just guessing , comparing the dead link `/game-of-life/debugging.html#building-with-debug-symbols` and a screenshot link (just underneath) `./images/game-of-life/profiler-with-rust-names.png` , it will probably work if I append `.` to the path.
Also it could be  just adding `/book` but as long as I'm not sure how test my changes I'm not able to send a PR.

**Comment by sigmaSd** [comment]
I think I found a similar issue : [https://github.com/rustwasm/wasm-bindgen/issues/569](https://github.com/rustwasm/wasm-bindgen/issues/569), the PR removed the leading `/`

**Comment by mgattozzi** [comment]
Wait so if you change the link to what I mentioned and click it, it doesn't open up the webpage at all? By adding the `/book` I mean. Ah try it with the `.` then. The `/book` might be the repo name for the GitHub Pages

**Comment by sigmaSd** [comment]
Cant believe I'm this bad at explaining the problem xD
Anyhow turn out its an issue with mdbook, version 0.1.9 messes up relative paths.
Probably similar to [https://github.com/rust-lang-nursery/mdBook/issues/746](https://github.com/rust-lang-nursery/mdBook/issues/746)
I downgraded to 0.1.8 and now I can reproduce the issue and test my changes .
Adding `.` to the path indeed fixes the issue.
