### ISSUE TITLE
Dead image links in Game of Life explanation

### ISSUE THREAD

**Issue by sarahmeyer** [rustwasm/book#64]
**Describe the bug**

**To Reproduce**
1. Go to `/src/game-of-life/rules.md`
2. Look for image with address `https://github.com/rustwasm/book/blob/master/src/game-of-life/images/game-of-life/initial-universe.png`
3. Look for image with address `https://github.com/rustwasm/book/blob/master/src/game-of-life/images/game-of-life/next-universe.png`
4. Go to `/src/game-of-life/implementing.md`
5. Look for image with address `https://github.com/rustwasm/book/blob/master/src/game-of-life/images/game-of-life/universe.png`
6. All images are missing due to 404

**Expected behavior**
Either no image tag or a valid image inside the image tag

**Screenshots**
![screen shot 2018-08-02 at 10 44 40 pm](https://user-images.githubusercontent.com/2723032/43621475-ae78d4f6-96a5-11e8-943c-445a59e3d93b.png)

**Comment by fitzgen** [comment]
Incidentally, the images should be fixed by #67 

However the recommended way to read the book is not by browsing the md files, but by looking at the hosted version at rustwasm.github.io/book
