### ISSUE TITLE
youtube embed iframe broken in `/src/game-of-life/rules.md`

### ISSUE THREAD

**Issue by sarahmeyer** [rustwasm/book#65]
**Describe the bug**
iframe html is just hanging out in the markdown

**To Reproduce**
1. Go to '/src/game-of-life/rules.md'
2. Look at bottom of page
3. YouTube embed is broken

**Expected behavior**
Working video or link out to YouTube

**Comment by fitzgen** [comment]
It works if you go to the hosted github pages version. GitHub sanitizes the html it will render on the page (as they should!) so it isn't really expected that this will work when just browsing the md files.
