### ISSUE TITLE
Add tests to the Game of Life tutorial

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/book#80]
Using `wasm-bindgen-test`: https://github.com/rustwasm/wasm-bindgen/tree/master/crates/test

**Comment by DebugSteven** [comment]
I'd like to help out on this issue.

**Comment by fitzgen** [comment]
@DebugSteven great! Again, don't hesitate to ask if you run into any questions :) Thanks!

**Comment by fitzgen** [comment]
Fixed by #137!
