### ISSUE TITLE
Add `wasm-bindgen-futures` to crates you should know section

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/book#81]
Its source is in the wasm-bindgen repo: https://github.com/rustwasm/wasm-bindgen/tree/master/crates/futures

This would go in the "Interacting with JavaScript and the DOM" section.'

Here it is on crates.io: https://crates.io/crates/wasm-bindgen-futures

Its API documentation has more details about what it is, and should be more than enough to inform what should go in the ~one paragraph summary that would be added to the crates you should know section: https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen_futures/

**Comment by fitzgen** [comment]
@wizofe assigned :)

**Comment by wizofe** [comment]
Done, thanks @fitzgen

**Comment by fitzgen** [comment]
Thanks for doing this @wizofe :)
