### ISSUE TITLE
npm link after npm install doesn't work

### ISSUE THREAD

**Issue by wizofe** [rustwasm/book#82]
**Where in the docs did you come across this?**
Section npm link and npm run:
https://rustwasm.github.io/book/game-of-life/hello-world.html

**Describe what about it does not make sense**
The sequence of the steps isn't correct, see below.

**Why does it not make sense?**
If it's run as described then the wasm-game-of-life won't be linked probably by npm and as result the program can't be launched

**How could we improve it?**
I sent already a PR, after figuring it out with the invaluable help of @fitzgen :pray:

**Comment by fitzgen** [comment]
Fixed in #83
