### ISSUE TITLE
No `www` dir created by the `npm init wasm-app www` command in the tutorial.

### ISSUE THREAD

**Issue by AaronM04** [rustwasm/book#94]
**Describe the bug**
No `www` dir created by the `npm init wasm-app www` command in the tutorial.

**To Reproduce**
1. cargo generate --git https://github.com/rustwasm/wasm-pack-template
2. Enter wasm-game-of-life for the project name
3. cd wasm-game-of-life
4. wasm-pack init
5. npm init wasm-app www
6. Observe that there is no `www` directory created, contrary to what is said in https://rustwasm.github.io/book/game-of-life/hello-world.html#putting-it-into-a-web-page

**Expected behavior**
I expected a `www` directory so that I could continue the tutorial.

**Comment by fitzgen** [comment]
Hi @AaronM04, thanks for filing an issue. Have you verified that your npm is up to date? https://rustwasm.github.io/book/game-of-life/setup.html#npm has instructions on doing that

**Comment by AaronM04** [comment]
Not yet. I'll have to check in several hours. Do you know of versions that would exhibit this behavior?

On September 17, 2018 10:05:03 AM PDT, Nick Fitzgerald <notifications@github.com> wrote:
>Hi @AaronM04, thanks for filing an issue. Have you verified that your
>npm is up to date?
>https://rustwasm.github.io/book/game-of-life/setup.html#npm has
>instructions on doing that
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rustwasm/book/issues/94#issuecomment-422094215

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fitzgen** [comment]
Another person had a very similar issue, and updating their npm install fixed the problem. That's how we ended up including that snippet in the setup instructions :)

I'm on `npm 6.2.0`, and the `www` directory is correctly generated for me.

**Comment by fitzgen** [comment]
FWIW, I recommend using `nvm` to manage node/npm installs (similar to rustup). This should allow you to update to newer npm on fedora. https://github.com/creationix/nvm

You can also just clone https://github.com/rustwasm/create-wasm-app into `www`, which is what is happening under the hood.

Thanks again for filing an issue!
